services:
  pgdatabase: # this will be the host name
    image: postgres:13
    # local dev secrets
    env_file:
      - .env-local
    volumes: 
      - ".abnormal_db:/var/lib/postgresql/data:rw"
    ports: # allows access to postgres on localhost:5432
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DEV_PG_USER -d $$DEV_PG_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      pgdatabase:
        condition: service_healthy # ensures postgres is up first

  dbt:
    build:
      context: ./dbt
      dockerfile: dbt.Dockerfile
    depends_on:
        pgdatabase:
          condition: service_healthy # ensures postgres is up first
    volumes:
      - ./dbt:/usr/app
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml